name: scrape

on:
  schedule:
    - cron: "0 3 * * *"

  workflow_dispatch:

jobs:
  scrape-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up python
        uses: actions/setup-python@v3.1.1
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run scraper script
        run: python script.py
      
      #- name: Set ENV var
      #  run: |
      #    echo "DATE=$(python -c 'import datetime as dt; print(dt.datetime.now().date())')" >> $GITHUB_ENV
      
      - name: Notify me
        run: |
          curl -d "repo scraper ran" ntfy.sh/car-repo-scraper
          
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9.0.0
        with:
          message: Update cars data
          default_author: github_actions
      
